site_base_url: "https://jsparkhtx.github.io/Houston-ISD-Daily"
show_title: "Greater Houston ISD Daily"
show_description: "Daily readouts of last-24-hour news about Greater Houston Independent School Districts."
show_author: "PlayHereHouston"
show_email: "you@example.com"
timezone: "America/Chicago"
max_articles: 12
max_chars_per_article: 2800
voice: "en-US-AriaNeural"     # edge-tts voice
voice_rate: "+0%"
retain_days: 14
episode_prefix: "houston-isd-roundup"
# whitelist_domains:
#   - "houstonchronicle.com"
#   - "abc13.com"
#   - "khou.com"
#   - "click2houston.com"
#   - "communityimpact.com"
#   - "houstonpublicmedia.org"
#   - "houstonisd.org"
#   - "fortbendisd.com"
#   - "katyisd.org"
#   - "humbleisd.net"
#   - "pasadenaisd.org"
#   - "springbranchisd.com"
#   - "springisd.org"
#   - "kleinisd.net"
#   - "yahoo.com"
#   - "chron.com"

# In config.yaml
rss_feeds:
  # Houston-area general/education
  - https://www.houstonpublicmedia.org/rss/education/
  - https://abc13.com/feed/              # ABC13 (general, we’ll filter by ISD terms)
  - https://communityimpact.com/rss/     # Community Impact (regional)
  - https://katytimes.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc
  - https://coveringkaty.com/feed/
  - https://www.fortbendstar.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc
  - https://www.baytownsun.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc
  - https://www.springisd.org/site/RSS.aspx?DomainID=4&ModuleInstanceID=984&PageID=1      # if 404, delete
  - https://www.aldineisd.org/feed/                                                         # if available
  - https://www.springbranchisd.com/feed/                                                   # if available
  - https://www.kleinisd.net/feed/                                                          # if available
  - https://www.pasadenaisd.org/feed/                                                       # if available
  - https://www.humbleisd.net/site/RSS.aspx?DomainID=4&ModuleInstanceID=123&PageID=1       # if available
  - https://www.ccisd.net/site/RSS.aspx?DomainID=4&ModuleInstanceID=38&PageID=1            # Clear Creek ISD (if RSS)
