name: Daily Build

on:
  schedule:
    - cron: "30 12 * * *"   # 12:30 UTC (~ morning Central)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build daily podcast
        run: |
          python src/main.py

      - name: Commit & push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Daily build"
            git push
          else
            echo "No changes to commit."
