name: Daily Build

on:
  workflow_dispatch:
  schedule:
    # 5:00 AM America/Chicago (handles DST with two cron lines)
    - cron: "0 10 * * *"   # 5:00 AM CT during Daylight Saving (CDT, UTC-5)
    - cron: "0 11 * * *"   # 5:00 AM CT during Standard Time (CST, UTC-6)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure timezone
        run: sudo timedatectl set-timezone America/Chicago

      - name: Run pipeline (skip TTS in CI)
        env:
          TZ: America/Chicago
          TTS_PROVIDER: none
        run: python -m src.main --date today --no-tts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: isd-episode
          path: |
            data/episodes/**
            data/feed/podcast.xml
